### ISSUE TITLE
Error: Error: can't convert to Destination COSArray{[COSNull{}, COSFloat{0.0}, COSFloat{0.0}, COSFloat{1.0}]}

### ISSUE THREAD

**Issue by sedimentation-fault** [Yanpas/PdfMerger#3]
### Attachment
[choi17a.pdf](https://github.com/Yanpas/PdfMerger/files/2464593/choi17a.pdf)

### Description

Trying to merge the attached single PDF file (no need to add a second file to merge in order to demonstrate the issue) with:

`java -jar pdfmerger-1.2.jar choi17a.pdf out.pdf`

I get:

```
Error: Error: can't convert to Destination COSArray{[COSNull{}, COSFloat{0.0}, COSFloat{0.0}, COSFloat{1.0}]}
Stack trace:
java.io.IOException: Error: can't convert to Destination COSArray{[COSNull{}, COSFloat{0.0}, COSFloat{0.0}, COSFloat{1.0}]}
        at org.apache.pdfbox.pdmodel.interactive.documentnavigation.destination.PDDestination.create(PDDestination.java:98)
        at org.apache.pdfbox.pdmodel.interactive.documentnavigation.outline.PDOutlineItem.getDestination(PDOutlineItem.java:188)
        at org.apache.pdfbox.pdmodel.interactive.documentnavigation.outline.PDOutlineItem.findDestinationPage(PDOutlineItem.java:230)
        at yanpas.pdfmerger.Merger.addOutlines(Merger.java:23)
        at yanpas.pdfmerger.Merger.appendDoc(Merger.java:62)
        at yanpas.pdfmerger.Merger.addDocument(Merger.java:68)
        at yanpas.pdfmerger.PdfMerger.main(PdfMerger.java:67)
```
This happens with both versions 1.0 and 1.2.

### Reason

This is probably due to the fact the the PDF contains a bookmark, '_Choi_Appendix.pdf_' that does not seem to be pointing anywhere - at least the viewers seems to ignore it.

### Workaround

As a temporary fix (workaround), eliminate bookmarks with empty targets from the PDFs you want to merge. For example, this version of the PDF in question, without the nowhere-pointing bookmark, works flawlessly:

[choi17a.pdf](https://github.com/Yanpas/PdfMerger/files/2464661/choi17a.pdf)

### Proposed solution

Ignore bookmarks that look invalid, instead of choking on them. Issue a warning, but add them nonetheless, possibly with an empty (or default, if 'empty' is not an option) target.

**Comment by Yanpas** [comment]
Thanks for pointing this out, fixed in bde5536 (release 1.2.1)

**Comment by Yanpas** [comment]
FYI, you can download compiled jar at the [releases](https://github.com/Yanpas/PdfMerger/releases) page

**Comment by sedimentation-fault** [comment]
Thank you very much. Yes, I've seen the releases page and I am using it already. Will try new version later.
BTW I might have some code examples to share, can I use the Wiki for that?

**Comment by Yanpas** [comment]
What do you mean by code examples? Source code is available under gpl3. Some long text files may be uploaded to github gist.

**Comment by sedimentation-fault** [comment]
I mean something like that:

> "If you have 500 PDFs to merge into one PDF, this may result in a 1GB file - which may not be what you want. You might want to split the files in groups - here's how: ..."

or:

> "You might have PDFs to merge coming from different directories, or having blanks in their names. In such cases, you cannot just pass them with '*.pdf' on the command line - you should gather their filenames in a list and then do: ..."

or:

...and so on. ;-)

Something that would go under _'Documentation'_, or better _'Examples of usage'_...
There is a [Wiki](https://github.com/Yanpas/PdfMerger/wiki) link for the project, but I guess you have to enable it first. Examples like the above would perfectly fit in a project Wiki.

**Comment by Yanpas** [comment]
I've created wiki.

> You might have PDFs to merge coming from different directories, or having blanks in their names

I think such tips better fit to some bash tutorial, something like
` { find . -name '*.pdf' ; echo out.pdf } | xargs pdfmerger `

**Comment by sedimentation-fault** [comment]
O.K., version 1.2.1 seems to have solved the problem with empty bookmarks.

For the Wiki, as far as I understand from [Changing access permissions for wikis](https://help.github.com/articles/changing-access-permissions-for-wikis/), you either have to make me a collaborator, or open access to Wiki for anyone with a GitHub account.

Your one-liner will not work if the filenames contain blanks (and I think you need round brackets, not curly ones). That's why it's nice to have a catalog of good examples.

**Comment by Yanpas** [comment]
I've opened an access to wiki.

Yes, spaces are ignored and curly braces don't work since I've forgot semicolon :) Also there are limitations is shell wrapper. More correct version:
`{ find . -name '*.pdf' ; echo out.pdf; } | xargs -0 java -jar pdfmerger.jar`

**Comment by Yanpas** [comment]
`xargs -d '\n'` seem to fix spaces issue
