### ISSUE TITLE
Bloody Cracking Bit of Code!!!

### ISSUE THREAD

**Issue by xpseudonym** [Yanpas/PdfMerger#4]
Don't know how to say thank you without lunching a bug to do so, but cat'ing a bunch of PDFs while building an bookmark outline is something so simple and yet has been impossible to find!
Thank you
(PS I did find it quite difficult to follow the documentation to set up - I found myself reading the source to find the docs and pdfmerger executable in order to work out where to put and how to run the binary as intended.)

**Comment by Yanpas** [comment]
Thanks

That instruction mostly for developers. If you don't want to compile from sources then go to releases page and download jar with the latest version. Then run it with java as any other jar. On windows you need to install JRE.

**Comment by xpseudonym** [comment]
Sorry to sound so slow - but, where is the releases page...?

**Comment by Yanpas** [comment]
![image](https://user-images.githubusercontent.com/7345761/63251822-cfccb000-c26e-11e9-9156-797bb62886f4.png)

Here it is https://github.com/Yanpas/PdfMerger/releases
